### ISSUE TITLE
Fix Turret Bugs

### ISSUE THREAD

**Issue by JustinH-94** [McChristie-Aidan/TwinStop#68]
The objective is to fix some issues with the turret. As of right now, the cannon doesn't explode, the player takes damage from the turret even though it should not be active.

**Comment by JustinH-94** [comment]
The bug turned out that there was a little mishap with the code for the audio, so I went ahead and patched that up. Also I made it so that the box collider is turned off for the parent gameobject, so now the player won't take damage when the Player touches it when it's destroyed.

**Comment by ProgramInc** [comment]
Hi! Can I contribute to your project? not necessarily to this issue as I understand that it's fixed in 2nd Alpha
